In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import silhouette_score
from sklearn.cluster import KMeans

In [2]:
#import dataset with redundant features removed
df_NBA_slim = pd.read_csv('NBA_numeric_slim.csv')
df_NBA_slim.head()

,season,age,w,sos,o_rtg,d_rtg,pace,f_tr,x3p_ar,ts_percent,...,away_orb_percent,away_opp_e_fg_percent,away_opp_tov_percent,away_opp_drb_percent,away_opp_ft_fga,away_attend,away_attend_g,home_score,away_score,spread
0,2005,26.0,13.0,0.09,100.6,111.1,91.4,0.299,0.146,0.504,...,27.2,0.481,14.2,70.1,0.274,656081.0,16002.0,120,117,3
1,2005,26.0,13.0,0.09,100.6,111.1,91.4,0.299,0.146,0.504,...,29.5,0.497,14.7,70.9,0.269,591701.0,14432.0,90,93,-3
2,2005,26.0,13.0,0.09,100.6,111.1,91.4,0.299,0.146,0.504,...,28.4,0.454,14.4,72.6,0.262,828384.0,20204.0,105,114,-9
3,2005,26.0,13.0,0.09,100.6,111.1,91.4,0.299,0.146,0.504,...,28.4,0.482,15.1,71.7,0.247,723949.0,17657.0,110,107,3
4,2005,26.0,13.0,0.09,100.6,111.1,91.4,0.299,0.146,0.504,...,31.2,0.461,13.5,73.0,0.207,905116.0,22076.0,68,95,-27

In [3]:
#looking to first cluster matches.  Remove season and targets.
df_data = df_NBA_slim.iloc[:,1:-3]
df_data.head()

,age,w,sos,o_rtg,d_rtg,pace,f_tr,x3p_ar,ts_percent,tov_percent,...,away_x3p_ar,away_ts_percent,away_tov_percent,away_orb_percent,away_opp_e_fg_percent,away_opp_tov_percent,away_opp_drb_percent,away_opp_ft_fga,away_attend,away_attend_g
0,26.0,13.0,0.09,100.6,111.1,91.4,0.299,0.146,0.504,14.9,...,0.192,0.551,14.7,27.2,0.481,14.2,70.1,0.274,656081.0,16002.0
1,26.0,13.0,0.09,100.6,111.1,91.4,0.299,0.146,0.504,14.9,...,0.128,0.497,13.3,29.5,0.497,14.7,70.9,0.269,591701.0,14432.0
2,26.0,13.0,0.09,100.6,111.1,91.4,0.299,0.146,0.504,14.9,...,0.217,0.517,15.5,28.4,0.454,14.4,72.6,0.262,828384.0,20204.0
3,26.0,13.0,0.09,100.6,111.1,91.4,0.299,0.146,0.504,14.9,...,0.142,0.535,13.8,28.4,0.482,15.1,71.7,0.247,723949.0,17657.0
4,26.0,13.0,0.09,100.6,111.1,91.4,0.299,0.146,0.504,14.9,...,0.164,0.519,13.3,31.2,0.461,13.5,73.0,0.207,905116.0,22076.0

In [4]:
#z-score normalize the data
ss = StandardScaler()

df_data_ss = ss.fit_transform(df_data)

In [10]:
%%time
#Kmeans cluster the data and calculate silhouette score

for k in range(2, 10):
    km = KMeans(n_clusters=k)
    km_matches = km.fit(df_data_ss)
    print(f"silhouette_score for {k} clusters =", silhouette_score(df_data, km_matches.labels_))
    
    """silhouette_score for 2 clusters = -0.0101992605149657
silhouette_score for 3 clusters = 0.007154211353900457
silhouette_score for 4 clusters = 0.006225659061462055
silhouette_score for 5 clusters = -0.029528129907441514
silhouette_score for 6 clusters = -0.058547797545294676
silhouette_score for 7 clusters = -0.0631273458804793
silhouette_score for 8 clusters = -0.08569728136575379
silhouette_score for 9 clusters = -0.10837161845447316"""
    
#so, that's pretty awful.  KMeans is not good at data that isn't spherical or that varies in density.
#need to play with this more

silhouette_score for 2 clusters = -0.0101992605149657
silhouette_score for 3 clusters = 0.007154211353900457
silhouette_score for 4 clusters = 0.006225659061462055
silhouette_score for 5 clusters = -0.029528129907441514
silhouette_score for 6 clusters = -0.058547797545294676
silhouette_score for 7 clusters = -0.0631273458804793
silhouette_score for 8 clusters = -0.08569728136575379
silhouette_score for 9 clusters = -0.10837161845447316
CPU times: total: 2min 5s
Wall time: 34 s